# -*- coding: utf-8 -*-
"""puliziaDatasetipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vI1eDURzNxPEx05cKZCR4Ii5Rglm8l0f
"""

import pandas as pd
from google.colab import data_table

data_table.enable_dataframe_formatter()
dataset=pd.read_csv("datasetRisposte.csv")
dataset


#rinomino le colonne per facilitare le operazioni
dataset.rename(columns={"Quali colori ti piacciono di più quando scegli un outfit?": "Colori"}, inplace=True)
dataset.rename(columns={"Preferisci outfit adatti a una stagione specifica? Se sì, quale?" : "Stagione"}, inplace=True)
dataset.rename(columns={"Quali sono i tipi di abbigliamento che preferisci?": "Tipo abbigliamento"}, inplace=True)
dataset.rename(columns={"Quanto è importante per te che un outfit sia comodo rispetto a essere alla moda?": "Comfort o stile?"}, inplace=True)
dataset



#numero di elementi che preferiscono lo stile alla comodità
count=dataset['Comfort o stile?'].value_counts()
print(count)
print(len(dataset))

dataset.describe()

#controllo valori nulli
nan_mask=dataset.isna()
nan_count=nan_mask.sum()

nan_count

dataset.info()

dataset['Colore1']=dataset['Colori'].apply(lambda x: x.split(',')[0])

dataset

nan_mask=dataset.isna()
nan_count=nan_mask.sum()

nan_count
"""Possiamo andare a suddividere la colonna Colori in tre colonnne contenenti un solo valore per semplificare le prossime operazioni
"""

dataset[['Colore1', 'Colore2', 'Colore3']] = dataset['Colori'].str.split(', ', expand=True)
dataset

dataset.info()

dataset.describe()

dataset.drop(['Informazioni cronologiche'], axis=1, inplace=True)
dataset

dataset.drop(['Colori'], axis=1, inplace=True)
dataset

dataset['Per quale occasione?'].value_counts()

dataset.rename(columns={"Per quale occasione?": "Evento"}, inplace=True)
dataset

dataset.to_csv('creazione_outfit.csv', index=False)


#controlliamo i valori nulli del dataset
nan_mask=dataset.isna()
nan_count=nan_mask.sum()

nan_count

"""Potremmo unire festa/discoteca e uscita con amici potendole considerare come occasioni simili

"""

def unisci_evento(Evento):
  if(Evento)=='Uscita con amici':
    return 'Svago'
  elif(Evento)=='Discoteca/festa':
    return 'Svago'
  else:
    return Evento

dataset['Evento']=dataset['Evento'].apply(unisci_evento)
dataset

"""Per quanto riguarda i valori nulli, il terzo colore è stato aggiunto poche volte(31 valori non nulli), L'unica strategia adottabile è eliminare la colonna dal dataset."""

dataset.drop('Colore3', axis=1, inplace=True)
dataset

"""Anche la colonna del comfort e lo stile ha dei valori nulli"""

dataset[dataset['Comfort o stile?'].isnull()]

"""Posso riempire il valore nullo in base alla tipologia di abbigliamento che l'utente ha inserito, se ha inserito 'Sportivo' o 'Casual' probabilmente preferirà la comodità allo stile"""

#creo una funzione che mi riempia i valori vuoti della colonna "Comfort o stile" in base al tipo di abbigliamento selezionato dall'utente

def riempi_valori(row):
  if pd.isnull(row['Comfort o stile?']):
    if row['Tipo abbigliamento']=='Sportivo' or row['Tipo abbigliamento']=='Casual':
      return 'Comodità'
    else:
      return 'Stile'

  dataset['Comfort o stile?']=dataset.apply(riempi_valori, axis=1)

  dataset

dataset

dataset[dataset['Comfort o stile?'].isnull()]

def riempi_val_nulli(row):
  if pd.isnull(row['Comfort o stile?']):
    if row['Tipo abbigliamento']=='Sportivo' or row['Tipo abbigliamento']=='Casual':
      return 'Comodità'
    elif row['Tipo abbigliamento']=='Formale' or row['Tipo abbigliamento']=='Elegante' or row['Tipo abbigliamento']=='Minimalista':
      return 'Stile'
  else:
    return row['Comfort o stile?']

dataset['Comfort o stile?']=dataset.apply(riempi_val_nulli, axis=1)

dataset

"""in questo modo i valori nulli sono stati sostituiti"""

nan_mask=dataset.isna()
nan_count=nan_mask.sum()

nan_count

"""Anche la sezione 'Evento' e 'Colore2' hanno dei valori nulli"""

dataset[dataset['Evento'].isnull()]

dataset[dataset['Colore2'].isnull()]


#eliminiamo le righe in cui il colore secondario è mancante

dataset=dataset.dropna(subset=['Colore2'])
dataset[dataset['Colore2'].isnull()]

dataset

"""Riempire i valori nulli nella sezione 'Evento' tramite una funzione che valuta in base alla tipologia dell'abbigliamento"""

dataset.to_csv('datasetRisposte2.csv', index=False)

dataset[dataset['Evento'].isnull()]

def fill_evento(row):
  if pd.isnull(row['Evento']):
    if row['Tipo abbigliamento']=='Sportivo' and row['Comfort o stile?']=='Comodità':
      return 'Svago'
    elif row['Tipo abbigliamento']=='Casual' and row['Comfort o stile?']=='Comodità':
      return 'Università/Scuola'
    elif row['Tipo abbigliamento']=='Minimalista' or row['Tipo abbigliamento']=='Formale' or row['Tipo abbigliamento']=='Elegante' and  row['Comfort o stile?']=='Stile':
      return 'Lavoro'
    elif row['Tipo abbigliamento']=='Minimalista' or row['Tipo abbigliamento']=='Formale' or row['Tipo abbigliamento']=='Elegante' and  row['Comfort o stile?']=='Comodità':
      return 'Occasione formale'
  else:
    return row['Evento']


  dataset['Evento']=dataset.apply(fill_evento, axis=1)

  dataset

def fill_evento(row):
  if pd.isnull(row['Evento']):
    if row['Tipo abbigliamento']=='Sportivo' and row['Comfort o stile?']=='Comodità':
      return 'Svago'
    elif row['Tipo abbigliamento']=='Casual' and row['Comfort o stile?']=='Comodità':
      return 'Università/Scuola'
    elif row['Tipo abbigliamento']=='Minimalista' or row['Tipo abbigliamento']=='Formale' or row['Tipo abbigliamento']=='Elegante' and  row['Comfort o stile?']=='Stile':
      return 'Lavoro'
    elif row['Tipo abbigliamento']=='Minimalista' or row['Tipo abbigliamento']=='Formale' or row['Tipo abbigliamento']=='Elegante' and  row['Comfort o stile?']=='Comodità':
      return 'Occasione formale'
  else:
    return row['Evento']

dataset['Evento']=dataset.apply(fill_evento, axis=1)

dataset

dataset[dataset['Evento'].isnull()]

def fill_evento2(row):
  if pd.isnull(row['Evento']):
    if row['Tipo abbigliamento']=='Sportivo' and row['Comfort o stile?']=='Stile':
      return 'Lavoro'
    elif row['Tipo abbigliamento']=='Casual' and row['Comfort o stile?']=='Stile':
      return 'Università/Scuola'
  else:
    return row['Evento']


dataset['Evento']=dataset.apply(fill_evento, axis=1)

dataset

dataset.loc[32, 'Evento']='Svago'
dataset

dataset.loc[48, 'Evento']='Lavoro'
dataset

nan_mask=dataset.isna()
nan_count=nan_mask.sum()

nan_count
